/**
 * Convert between a molecule unpacked result and JSON ready JavaScript value.
 * @module
 * @example
 * ```ts
 * import { json, factory, BuildingPacket } from "@ckb-cobuild/cobuild";
 * const buildingPacketJson = JSON.stringify(
 *   json.toJson(factory.makeBuildingPacket()),
 * );
 * const parsed = json.fromJson(BuildingPacket, JSON.parse(buildingPacketJson));
 * ```
 */
import { BI } from "@ckb-lumos/bi";
import { bytes, AnyCodec, PackParam, UnpackResult } from "@ckb-lumos/codec";

/* eslint-disable @typescript-eslint/no-explicit-any */

type CompatibleType = string | boolean | null;
type HexStringType = number | BI | Uint8Array;

/**
 * @example The corresponding Json value type of BuildingPacket
 * ```ts
 * JsonValue<BuildingPacket>
 * ```
 */
export type JsonValue<T> = T extends CompatibleType
  ? T
  : T extends undefined
    ? null
    : T extends HexStringType
      ? string
      : T extends Array<infer U>
        ? JsonArray<U>
        : JsonMap<T>;
type JsonArray<T> = Array<JsonValue<T>>;
type JsonMap<T> = {
  [K in keyof T]: JsonValue<T[K]>;
};

/**
 * Convert molecule unpack result to Json ready JavaScript value.
 *
 * The Json follows CKB JSONRPC convention which represents number, {@link BI}, Uint8Array as hex strings.
 * @param value - Unpack Result generated by molecule codec unpack method.
 */
export function toJson<T = any>(value: T): JsonValue<T> {
  // Narrowing does not work here
  if (
    typeof value === "string" ||
    typeof value === "boolean" ||
    value === null
  ) {
    return value as JsonValue<T>;
  }
  if (typeof value === "number") {
    return BI.from(value).toHexString() as JsonValue<T>;
  }
  if (typeof value === "object") {
    if (value instanceof BI) {
      return value.toHexString() as JsonValue<T>;
    }
    if (value instanceof Uint8Array) {
      return bytes.hexify(value) as JsonValue<T>;
    }
    if (Array.isArray(value)) {
      return value.map(toJson) as JsonValue<T>;
    }

    const result: Record<string, any> = {};
    for (const [propertyName, propertyValue] of Object.entries(value)) {
      result[propertyName] = toJson(propertyValue);
    }
    return result as JsonValue<T>;
  }

  return (value !== undefined ? value : null) as JsonValue<T>;
}

/**
 * Convert a Json value to the codec unpacked result.
 *
 * Internnly, this function packs the Json value and then unpacks.
 *
 * @example
 * ```ts
 * import { json, BuildingPacket } from "@ckb-cobuild/cobuild";
 * const parsed = json.fromJson(BuildingPacket, JSON.parse("{}"));
 * ```
 */
export function fromJson(
  codec: AnyCodec,
  jsonValue: PackParam<AnyCodec>,
): UnpackResult<AnyCodec> {
  return codec.unpack(codec.pack(jsonValue));
}
